### ISSUE TITLE
aiplatform: PredictionServiceClient throws UNAUTHENTICATED when credentials are provided using FixedCredentialsProvider

### ISSUE THREAD

**Issue by bladekp** [googleapis/java-aiplatform#1056]
#### Environment details

1. OS type and version: Fedora Linux 35, kernel 5.19.9-100.fc35.x86_64
2. Java version: 17.0.1 Temurin
3. Tested on `com.google.cloud:google-cloud-aiplatform:2.6.0`, `com.google.cloud:google-cloud-aiplatform:3.0.0`, `com.google.cloud:google-cloud-aiplatform:3.3.0` (with other dependencies versions (like `com.google.auth:google-auth-library-oauth2-http`) provided by `com.google.cloud:libraries-bom`).
4. My `pom.xml`:
```
...
        <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.google.cloud</groupId>
				<artifactId>libraries-bom</artifactId>
				<version>${google-cloud-libraries-bom.vesrion}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
...
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-aiplatform</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.auth</groupId>
            <artifactId>google-auth-library-oauth2-http</artifactId>
        </dependency>
...
```

#### Steps to reproduce

1. Set `GOOGLE_APPLICATION_CREDENTIALS` env variable `export GOOGLE_APPLICATION_CREDENTIALS="/valid/path/to/file.json"`. 
2. Create `PredictionServiceClient` with default credentials provider:
```java
 PredictionServiceSettings predictionServiceSettings = PredictionServiceSettings.newBuilder().setEndpoint(...) .build();
 PredictionServiceClient predictionServiceClient = PredictionServiceClient.create(predictionServiceSettings);
```
3. Execute prediction `predictionServiceClient.predict(...)`. Everything works as expected.
6. Now clear `GOOGLE_APPLICATION_CREDENTIALS` env variable `export GOOGLE_APPLICATION_CREDENTIALS=""`.
7. Create `PredictionServiceClient` with `FixedCredentialsProvider` using same json file with credentials as above, also add file to the classpath:
```java
CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(GoogleCredentials.fromStream(new ClassPathResource("file.json").getInputStream()));
PredictionServiceSettings predictionServiceSettings = PredictionServiceSettings.newBuilder().setCredentialsProvider(credentialsProvider).setEndpoint("...") .build();
PredictionServiceClient predictionServiceClient = PredictionServiceClient.create(predictionServiceSettings);
```
8. Execute prediction `predictionServiceClient.predict(...)`. Now the exception is thrown by the client:
```
com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:71) ~[gax-2.11.0.jar:2.11.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-2.11.0.jar:2.11.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-2.11.0.jar:2.11.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-2.11.0.jar:2.11.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-2.1.3.jar:na]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1277) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808) ~[guava-31.0.1-jre.jar:na]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:564) ~[grpc-stub-1.44.0.jar:1.44.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:534) ~[grpc-stub-1.44.0.jar:1.44.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.44.0.jar:1.44.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.44.0.jar:1.44.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.44.0.jar:1.44.0]
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:455) ~[gax-grpc-2.11.0.jar:2.11.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.44.0.jar:1.44.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.44.0.jar:1.44.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-2.11.0.jar:2.11.0]
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-2.11.0.jar:2.11.0]
		at com.google.cloud.aiplatform.v1.PredictionServiceClient.predict(PredictionServiceClient.java:256) ~[google-cloud-aiplatform-2.6.0.jar:2.6.0]
		at com.google.cloud.aiplatform.v1.PredictionServiceClient.predict(PredictionServiceClient.java:189) ~[google-cloud-aiplatform-2.6.0.jar:2.6.0]
		at a.b.x(M.java:99) ~[classes/:na]
		at a.b.h(W.java:99) ~[classes/:na]
		at a.b.e.lambda$f$6(G.java:99) ~[classes/:na]
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
		at a.b.c(D.java:99) ~[classes/:na]
		at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63) ~[rxjava-3.1.5.jar:na]
		at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58) ~[rxjava-3.1.5.jar:na]
		at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202) ~[rxjava-3.1.5.jar:na]
		at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256) ~[rxjava-3.1.5.jar:na]
		at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) ~[rxjava-3.1.5.jar:na]
		at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) ~[rxjava-3.1.5.jar:na]
		at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		... 3 common frames omitted
```

#### Any additional information below

- Im using the very same `FixedCredentialsProvider` with the same credentials json file to access GCP Storage and GCP Vision API, and it works well.
- When I provide the credentials using `GOOGLE_APPLICATION_CREDENTIALS` env variable, everything works well, so probably my service account have all required permissions to execute predict endpoint.

**Comment by alicejli** [comment]
Hi! I suspect the failure may be because you need to add scopes to the Credentials when you create them from `FixedCredentialsProvider`. Can you try something similar to the following:

```
CredentialsProvider credentialsProvider =
    FixedCredentialsProvider.create(
        GoogleCredentials.fromStream(new ClassPathResource("file.json").getInputStream())
            .createScoped(PredictionServiceSettings.getDefaultServiceScopes()));
```

**Comment by bladekp** [comment]
Ok, thanks this works, scope that I needed was `https://www.googleapis.com/auth/cloud-platform`, which indeed could be provided like `PredictionServiceSettings.getDefaultServiceScopes()`. Thanks for help.

Reference of scopes: https://developers.google.com/identity/protocols/oauth2/scopes?hl=en
