### ISSUE TITLE
java-aiplatform: ExceptionInInitializerError at com.google.api.gax.core.GaxProperties.getJavaVersion when using PredictionServiceSettings.newBuilder()

### ISSUE THREAD

**Issue by ThomasCookLush** [googleapis/java-aiplatform#989]
#### Environment details

1. java-aiplatform; specifically usage of the `PredictionServiceSettings` class

2. environment information:
- android application
- building from Windows 10 environment using `AS Dolphin 2021.3.1 Beta 4`
- `gradle 7.2.1`
- `kotlin-gradle-plugin 1.5.31`

#### Steps to reproduce:

- Follow the documentation here https://cloud.google.com/vertex-ai/docs/start/client-libraries and https://cloud.google.com/vertex-ai/docs/predictions/online-predictions-automl#classification
- Build and deploy app
- Upon invoking `PredictionServiceSettings.newBuilder()` the app crashes

#### Code example

```java
private const val ENDPOINT_ID="PRIVATE"
private const val PROJECT_ID="PRIVATE"
private const val ENDPOINT_LOCATION = "us-central1"

class RecognitionInteractorImpl {

    fun getRecognitionResult(
        content: String
    ): RecognitionResultDisplayItem {
        val predictionServiceSettingsBuilder = PredictionServiceSettings.newBuilder() // Crashes here
        predictionServiceSettingsBuilder.setEndpoint("us-central1-aiplatform.googleapis.com:443")
        val predictionServiceSettings = predictionServiceSettingsBuilder.build()
        val predictionServiceClient = PredictionServiceClient
            .create(predictionServiceSettings)

        val endpointName = EndpointName.of(PROJECT_ID, ENDPOINT_LOCATION, ENDPOINT_ID)

        val predictionInstance = ImageClassificationPredictionInstance
            .newBuilder()
            .setContent(content)
            .build()

        val instances = listOf(ValueConverter.toValue(predictionInstance))

        val predictionParams = ValueConverter.toValue(
            ImageClassificationPredictionParams
                .newBuilder()
                .setConfidenceThreshold(0.5f)
                .setMaxPredictions(5)
                .build()
        )

        val predictionResponse = predictionServiceClient.predict(
            endpointName,
            instances,
            predictionParams
        )

        return RecognitionResultDisplayItem(
            recognitionDisplayItems = predictionResponse.predictionsList.flatMap { prediction ->
                val resultBuilder = ClassificationPredictionResult.newBuilder()
                val result = ValueConverter.fromValue(resultBuilder, prediction) as ClassificationPredictionResult
                List(result.idsList.size) { index ->
                    RecognitionDisplayItem(
                        id = result.getIds(index),
                        name = result.getDisplayNames(index),
                        confidence = result.getConfidences(index)
                    )
                }
            }
        )
    }
}
```

#### Stack trace
```
FATAL EXCEPTION: main
    Process: com.lush.wellbeing, PID: 11728
    java.lang.ExceptionInInitializerError
        at com.google.api.gax.core.GaxProperties.getJavaVersion(GaxProperties.java:89)
        at com.google.api.gax.rpc.ApiClientHeaderProvider$Builder.<init>(ApiClientHeaderProvider.java:115)
        at com.google.api.gax.rpc.ApiClientHeaderProvider.newBuilder(ApiClientHeaderProvider.java:89)
        at com.google.cloud.aiplatform.v1.stub.PredictionServiceStubSettings.defaultApiClientHeaderProviderBuilder(PredictionServiceStubSettings.java:264)
        at com.google.cloud.aiplatform.v1.stub.PredictionServiceStubSettings$Builder.createDefault(PredictionServiceStubSettings.java:391)
        at com.google.cloud.aiplatform.v1.stub.PredictionServiceStubSettings$Builder.access$100(PredictionServiceStubSettings.java:300)
        at com.google.cloud.aiplatform.v1.stub.PredictionServiceStubSettings.newBuilder(PredictionServiceStubSettings.java:273)
        at com.google.cloud.aiplatform.v1.PredictionServiceSettings$Builder.createDefault(PredictionServiceSettings.java:204)
        at com.google.cloud.aiplatform.v1.PredictionServiceSettings$Builder.access$000(PredictionServiceSettings.java:185)
        at com.google.cloud.aiplatform.v1.PredictionServiceSettings.newBuilder(PredictionServiceSettings.java:167)
        at com.lush.recognition.interactors.RecognitionInteractor.getRecognitionResult(RecognitionInteractor.kt:23)
        at com.lush.wellbeing.recognition.fragments.ProductRecognitionFragment$$ExternalSyntheticLambda1.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:638)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at android.app.Activity.dispatchActivityResult(Activity.java:8388)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)
        at java.util.jar.JarVerifier.update(JarVerifier.java:229)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:393)
        at java.util.jar.JarFile.getInputStream(JarFile.java:460)
        at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
```

#### External references such as API reference guides

- https://cloud.google.com/vertex-ai/docs/start/client-libraries
- https://cloud.google.com/vertex-ai/docs/predictions/online-predictions-automl#classification

**Comment by ThomasCookLush** [comment]
Nothing really to do with the library, had to do with misconfigured gradle files
