### ISSUE TITLE
java-aiplatform - io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found

### ISSUE THREAD

**Issue by ThomasCookLush** [googleapis/java-aiplatform#990]
#### Sumary
Failing to build `PredictionServiceSettings` class when passing custom credentials provider, loading service account from bundled JSON file.

I am creating an Android application which will be used to call a vertex AI endpoint. I have chosen to use the java client library in this Android app, which I'm attempting to do by following the documentation here: https://cloud.google.com/vertex-ai/docs/start/client-libraries.

After some teething issues I have come to the conclusion that this library is currently for usage in desktop applications or server applications using Java, rather than primarily for Android. I came to this conclusion because the documentation assumes that the consumer will set `GOOGLE_APPLICATION_CREDENTIALS` environment variable pointing to the service account JSON, which will then be used at runtime to resolve credentials for the `PredictionServiceSettings` (i.e. as per the code comment "Credentials are acquired automatically through Application Default Credentials."), however setting environment variables like this for Android apps is not possible as far as I know.

Therefore, I have decided to bundle the service account JSON into my apps resource/raw folder and load this file to create `GoogleCredentials` myself at runtime to override the libraries default behaviour of looking for these credentials via the file at the path specified  on the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.

The code is compiling, but it fails at runtime with:

`io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found`

Code and stack trace are below.

#### Environment details

1. java-aiplatform; specifically usage of the `PredictionServiceSettings` class

2. environment information:
- android application
- building from Windows 10 environment using `AS Dolphin 2021.3.1 Beta 4`
- `gradle 7.2.1`
- `kotlin-gradle-plugin 1.5.31`

#### Steps to reproduce:

- Follow the documentation here https://cloud.google.com/vertex-ai/docs/start/client-libraries and https://cloud.google.com/vertex-ai/docs/predictions/online-predictions-automl#classification
- Put service account JSON in `resources/raw` as realize that relying on environment variable for `GOOGLE_APPLICATION_CREDENTIALS` not suitable for Android application (presume this advice is for server applications using Java?)
- Create custom `CredentialsProvider` to load `GoogleCredentials` from stream using bundled JSON file from previous step
- Upon invoking `PredictionServiceSettings.build()` the app crashes (see stack trace after code sample).

#### Code example

Gradle:

```gradle
dependencies {
    def google_ai_platform_version = '3.0.0'
    def google_oauth_version = '1.8.0'

    implementation "com.google.cloud:google-cloud-aiplatform:$google_ai_platform_version"
    implementation "com.google.auth:google-auth-library-oauth2-http:$google_oauth_version"
}
```

Kotlin:
```kotlin
import android.app.Application
import com.google.api.gax.core.CredentialsProvider
import com.google.auth.oauth2.GoogleCredentials
import com.google.cloud.aiplatform.util.ValueConverter
import com.google.cloud.aiplatform.v1.EndpointName
import com.google.cloud.aiplatform.v1.PredictionServiceClient
import com.google.cloud.aiplatform.v1.PredictionServiceSettings
import com.google.cloud.aiplatform.v1.schema.predict.instance.ImageClassificationPredictionInstance
import com.google.cloud.aiplatform.v1.schema.predict.params.ImageClassificationPredictionParams
import com.google.cloud.aiplatform.v1.schema.predict.prediction.ClassificationPredictionResult
import com.lush.wellbeing.recognition.displayitems.RecognitionDisplayItem
import com.lush.wellbeing.recognition.displayitems.RecognitionResultDisplayItem

private const val ENDPOINT_ID="PRIVATE"
private const val PROJECT_ID="PRIVATE"
private const val ENDPOINT_LOCATION = "us-central1"

class RecognitionInteractorImpl(
    private val application: Application
) {

    fun getRecognitionResult(
        content: String
    ): RecognitionResultDisplayItem {
        val predictionServiceSettingsBuilder = PredictionServiceSettings.newBuilder()
        predictionServiceSettingsBuilder.credentialsProvider = CredentialsProvider {
            GoogleCredentials.fromStream(
                application.resources.openRawResource(
                    application.resources.getIdentifier("vertex_service_account", "raw", application.packageName)
                )
            ).createScoped(listOf(
                "https://www.googleapis.com/auth/cloud-platform"
            ))
        }
        predictionServiceSettingsBuilder.endpoint = "us-central1-aiplatform.googleapis.com:443"
        val predictionServiceSettings = predictionServiceSettingsBuilder.build()

        val predictionServiceClient = PredictionServiceClient
            .create(predictionServiceSettings)

        val endpointName = EndpointName.of(PROJECT_ID, ENDPOINT_LOCATION, ENDPOINT_ID)

        val predictionInstance = ImageClassificationPredictionInstance
            .newBuilder()
            .setContent(content)
            .build()

        val instances = listOf(ValueConverter.toValue(predictionInstance))

        val predictionParams = ValueConverter.toValue(
            ImageClassificationPredictionParams
                .newBuilder()
                .setConfidenceThreshold(0.5f)
                .setMaxPredictions(5)
                .build()
        )

        val predictionResponse = predictionServiceClient.predict(
            endpointName,
            instances,
            predictionParams
        )

        return RecognitionResultDisplayItem(
            recognitionDisplayItems = predictionResponse.predictionsList.flatMap { prediction ->
                val resultBuilder = ClassificationPredictionResult.newBuilder()
                val result = ValueConverter.fromValue(resultBuilder, prediction) as ClassificationPredictionResult
                List(result.idsList.size) { index ->
                    RecognitionDisplayItem(
                        id = result.getIds(index),
                        name = result.getDisplayNames(index),
                        confidence = result.getConfidences(index)
                    )
                }
            }
        )
    }
}
```

#### Stack trace
```java
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:45)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:350)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.$r8$lambda$uvhXwQKV1b6n5wSR9q5C4LYdHSs(Unknown Source:0)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$$ExternalSyntheticLambda0.createSingleChannel(Unknown Source:2)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:105)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:83)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:236)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:230)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)
	at com.google.cloud.aiplatform.v1.stub.GrpcPredictionServiceStub.create(GrpcPredictionServiceStub.java:146)
	at com.google.cloud.aiplatform.v1.stub.PredictionServiceStubSettings.createStub(PredictionServiceStubSettings.java:218)
	at com.google.cloud.aiplatform.v1.PredictionServiceClient.<init>(PredictionServiceClient.java:151)
	at com.google.cloud.aiplatform.v1.PredictionServiceClient.create(PredictionServiceClient.java:133)
	at com.lush.wellbeing.recognition.interactors.RecognitionInteractorImpl.getRecognitionResult(RecognitionInteractorImpl.kt:43)
	at com.lush.wellbeing.recognition.viewmodels.ProductRecognitionViewModelImpl.onImageCaptured(ProductRecognitionViewModelImpl.kt:42)
	at com.lush.wellbeing.recognition.fragments.ProductRecognitionFragment.activityResultLauncher$lambda-2(ProductRecognitionFragment.kt:48)
	at com.lush.wellbeing.recognition.fragments.ProductRecognitionFragment.$r8$lambda$L6dHy0Om-Y2BwzCF2PyCAwXvyBs(Unknown Source:0)
	at com.lush.wellbeing.recognition.fragments.ProductRecognitionFragment$$ExternalSyntheticLambda1.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:638)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:8388)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5361)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5407)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

#### External references such as API reference guides

- https://cloud.google.com/vertex-ai/docs/start/client-libraries
- https://cloud.google.com/vertex-ai/docs/predictions/online-predictions-automl#classification

**Comment by meltsufin** [comment]
If you have a support contract, please try reaching out though Google Cloud Support. Thanks!
